# Generated by Django 3.0 on 2020-03-28 10:53

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('posts', '0009_auto_20200126_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name=''),
        ),
    ]
