# Generated by Django 3.0 on 2020-01-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_auto_20191226_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='discipline',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='staff_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
