# Generated by Django 3.0 on 2020-03-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200312_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year_of_entrance',
            field=models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], default='2020', max_length=10),
        ),
    ]
