# Generated by Django 3.0 on 2020-03-19 11:30

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('account', '0010_auto_20200318_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=taggit.managers.TaggableManager(help_text='football, programming, photography', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Interests'),
        ),
    ]
