# Generated by Django 3.0 on 2020-03-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200319_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allow_messages',
        ),
    ]
