# Generated by Django 3.0 on 2020-03-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_profile_allow_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
