# Generated by Django 3.0 on 2020-01-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200130_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='year_of_entrance',
            new_name='entrance_year',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='year_of_graduation',
            new_name='graduation_year',
        ),
    ]
