# Generated by Django 3.0 on 2020-01-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200130_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year_of_entrance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year_of_graduation',
        ),
        migrations.AddField(
            model_name='profile',
            name='entrance_year',
            field=models.CharField(blank=True, choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=10, null=True),
        ),
    ]
