# Generated by Django 3.0 on 2020-04-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
