# Generated by Django 3.0 on 2020-04-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messageproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageproperty',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='messageproperty',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
