# Generated by Django 3.0 on 2020-04-30 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20200429_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
